server:
  port: 9000

spring:
  data:
    mongodb:
      database: ApexHire
      uri: ${MONGODB_URI:mongodb://localhost:27017/ApexHire}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:900000}

# 900000 ms = 15 minutes.

frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:5173}

# Python Resume Service Configuration
python:
  resume-service:
    url: ${PYTHON_RESUME_SERVICE_URL}
    api-key: ${PYTHON_RESUME_SERVICE_API_KEY}
    timeout: ${PYTHON_RESUME_SERVICE_TIMEOUT:60s}

# Resume File Storage Configuration
resume:
  file-storage:
    location: ${RESUME_FILE_STORAGE_LOCATION:storage}
    max-size: ${RESUME_MAX_FILE_SIZE:10485760}